version: "3"
services:
  hub_service:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome_service:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub_service
    environment:
      - HUB_HOST=hub_service